# Generated by Django 5.1.2 on 2024-11-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipic', '0002_customuser'),
    ]

    operations = [
    ]
