# Generated by Django 5.1.2 on 2024-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_path', models.FilePathField(path='ml/models/')),
                ('trained_on', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
