# Generated by Django 5.1.2 on 2024-11-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainedModel',
        ),
    ]
